### ISSUE TITLE
msgpack v4 is deprecated and should be replaced with msgpack v5

### ISSUE THREAD

**Issue by lizthegrey** [honeycombio/libhoney-go#115]

**Comment by paulosman** [comment]
In progress in [paul.msgpackv5](https://github.com/honeycombio/libhoney-go/tree/paul.msgpackv5). Tests are failing at the moment. The smallest repro case is:

```
package main

import (
	"bytes"
	"fmt"

	"github.com/honeycombio/libhoney-go/transmission"
	"github.com/vmihailenco/msgpack/v5"
)

func main() {
	var buf bytes.Buffer
	var err error

	e := &transmission.Event{SampleRate: 1}
	e.Data = map[string]interface{}{
		"h": map[int]int{
			1: 1,
		},
	}
	err = msgpack.NewEncoder(&buf).Encode(e)
	if err != nil {
		fmt.Println(err)
	}

	var decoded interface{}
	err = msgpack.NewDecoder(&buf).Decode(&decoded)
	if err != nil {
		fmt.Println("Could not decode.", err)
	}
}
```

Running this results in the following error message:

```
$ go run main.go
Could not decode. msgpack: invalid code=d3 decoding string/bytes length
```

Not that other kinds of maps work - it appears that a map of `int` to anything is what fails. (tested that `map[string]int`, `map[string]interface{}`, etc succeed while `map[int]string`, `map[int]interface{}`, etc fails).

**Comment by MikeGoldsmith** [comment]
Closing as I believe #127 has fixed this.
