### ISSUE TITLE
Documentation for msgpack encoding

### ISSUE THREAD

**Issue by jsha** [honeycombio/libhoney-go#124]
Related to #123: I see there are some dependencies in support of a "msgpack" encoding feature. [The docs say](https://pkg.go.dev/github.com/honeycombio/libhoney-go@v1.15.2/transmission#Honeycomb):

```
	// set true to send events with msgpack encoding
	EnableMsgpackEncoding bool
```

But it's not clear what the advantages and disadvantages are. I'd be interested to know if msgpack offers big enough benefits that we should definitely turn it on. If it does not offer large benefits, I would be interested in finding a way to remove the dependency for clients that don't turn it on.

**Comment by MikeGoldsmith** [comment]
Hey @jsha - thanks again for creating the issue.

As said in #123 - we would need to break up our packages to provide optional dependencies and this isn't something we plan on doing.

FYI we prefer the msgpack format as it offers a better compression ratio and decompression time than regular JSON.
