### ISSUE TITLE
Improve performance of event maps

### ISSUE THREAD

**Issue by kentquirk** [honeycombio/libhoney-go#198]
**Is your feature request related to a problem? Please describe.**
The maps used to store events are sized at 0 initially and grow as fields are added. This is expensive in Go when it hits reallocation boundaries. 

**Describe the solution you'd like**
Start with non-zero sizes for maps so that they require fewer reallocations. Make it configurable so that existing behavior won't change unless desired.

**Describe alternatives you've considered**

**Additional context**

**Comment by MikeGoldsmith** [comment]
Resolved by #197
