### ISSUE TITLE
Import of testing package causes testing flags to be registered

### ISSUE THREAD

**Issue by vcabbage** [honeycombio/libhoney-go#20]
When the `testing` package is imported it registers a number of global flags (https://github.com/golang/go/issues/21051). Since the `test_helpers.go` file in this project imports `testing`, any project that imports this library will get those flags.

Can `test_helpers.go` be renamed to have the `_test.go` suffix, `helpers_test.go` for example, so that it will be excluded from compilation when not running tests?

Thank you.

**Comment by christineyen** [comment]
Hi! Thanks for the report, hoping to get a fix out for this soon.

**Comment by adihoney** [comment]
This should be resolved in 1.6.0: https://github.com/honeycombio/libhoney-go/releases/tag/v1.6.0

Thanks again!
