### ISSUE TITLE
Reinstate statsd export

### ISSUE THREAD

**Issue by willem-i-am** [honeycombio/libhoney-go#206]
**Is your feature request related to a problem? Please describe.**

Since PR #40 the default behaviour has been changed so `statsd` metrics are hard-coded to not be exported.

It would be good if `statsd` export was configurable, with the default being off, so users of honeyaws could export the metrics if they so wished.

From looking at the code, it seems that to do this in the most simple manner would entail adding fields to the `Config` and `Client` structs. However, I wasn't sure if it's correct to add a `statsd` object to the `Client` because presumably this might lead to an incorrect number of `statsd` objects being instantiated.

I'm happy to work on a PR if you could provide some guidance as to the right approach.

**Describe the solution you'd like**

`statsd` export was configurable, with the default being off, so users of honeyaws could export the metrics if they so wished.

**Describe alternatives you've considered**

**Additional context**

**Comment by kentquirk** [comment]
Hi, @willem-i-am. 

Thank you for the request. The short version is that we don't intend to change libhoney-go or honeyaws to do this. 

The long version is that both of those repositories are considered to be in "[Maintained](https://github.com/honeycombio/home/blob/main/honeycomb-oss-lifecycle-and-practices.md)" status, which means we have no plans to add new features.

For the future, Honeycomb is a strong supporter of OpenTelemetry, which has standards for metrics, and we also have a set of [agentless integrations for aws](https://github.com/honeycombio/agentless-integrations-for-aws). If either of those could be made to fit your use case, I'd definitely encourage that, as it will be the best-supported way forward here.

If not, I'd suggest this:
 
A client of libhoney, if it needs a special configuration, should create a configuration that includes a Transmission, and that Transmission could include a Metrics provider which could be statsd. You could do this with a fork of the honeyaws repository and changes to the Publisher object.

I'm sorry we can't be more helpful, but we're a small team with limited resources.
