### ISSUE TITLE
Marker API

### ISSUE THREAD

**Issue by keegancsmith** [honeycombio/libhoney-go#25]
Any plans to expose the Marker API in this package? The API is nice and simple so is easy enough via `http.Client`, but hooking in to using the same `X-Honeycomb-Team` would be convenient.

**Comment by christineyen** [comment]
Hey Keegan, sorry for the delay -- this kicked off the latest iteration of an internal conversation about whether to expand the various `libhoney`s to manipulate APIs other than the main event-sending API.

Sounds like we're leaning towards "yes," though without a definite timeline - we'll be sure to update this issue when it happens! Thanks for the ping.

**Comment by MikeGoldsmith** [comment]
We’re going to close this as it's gone stale. Feel free to re-open, if it’s still relevant.
