### ISSUE TITLE
Cut a new release?

### ISSUE THREAD

**Issue by dynamike** [honeycombio/libhoney-go#29]
We are using [dep](https://golang.github.io/dep/) for dependency management, and when importing [beeline-go](https://github.com/honeycombio/beeline-go), `dep` is choosing to import the latest version of libhoney-go (`v.1.6.0`). The problem is [beeline-go](https://github.com/honeycombio/beeline-go) depends on some unreleased changes in libhoney-go
* https://github.com/honeycombio/libhoney-go/pull/26 
* https://github.com/honeycombio/libhoney-go/pull/24

Can someone cut a new release?

**Comment by emfree** [comment]
Good catch. New release `v1.7.0` is up: https://github.com/honeycombio/libhoney-go/releases/tag/v1.7.0 . Please let us know if you run into any other issues!
