### ISSUE TITLE
msgpack/v4 branch no longer exists

### ISSUE THREAD

**Issue by jdub** [honeycombio/libhoney-go#77]
Entertainingly, the v4 branch of msgpack [no longer exists](https://github.com/vmihailenco/msgpack/branches), which breaks non-module builds that depend on libhoney-go. I have also reported the [issue upstream](https://github.com/vmihailenco/msgpack/issues/264).

**Comment by vmihailenco** [comment]
I've created v4 branch, but I did not delete v4 - it never existed. I believe it was working as long as there was no v5. Which is understandable but still surprising.

**Comment by jdub** [comment]
Thanks @vmihailenco – Vladimir created the v4 branch, so I'll close this issue now.

**Comment by jdub** [comment]
I have created a gopkg.in-based solution to fix libhoney-go's vmihailenco/msgpack v4 dependency for non-modules users.

**Comment by lizthegrey** [comment]
This fix introduces another bug :(

https://github.com/honeycombio/libhoney-go/pull/79#issuecomment-659010133

**Comment by lizthegrey** [comment]
We have two paths forward to unbreak things for non-module users on modern golang1.13+:
(1) Get Github's Dependabot team to fix https://github.com/dependabot/gomodules-extracted/issues/5, and then de-support go1.12 (including the module users)
(2) Get @vmihailenco to change the canonical package name of msgpack library to use gopkg.in going forward, which would enable go1.12 module users, go1.13+ module users, and non-module users on any golang version to all be happy at the cost of having to add a replace directive or changing their import paths.

**Comment by lizthegrey** [comment]
(2) is not planned, and instead the proposed solution is to default to msgpack v5 branch.
